on:
  pull_request: ~
  push:
    branches:
      - "main"
      - "[0-9].*"

name: Coding Standards

jobs:
  codestyle:
    name: Codestyle

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 8.1 # Always run on the lowest supported version due to compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: curl
          php-version: ${{ matrix.php-version }}

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: |
          composer install --no-interaction --no-progress --optimize-autoloader

      - name: Run laravel/pint
        run: |
          vendor/bin/pint

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"