on:
  pull_request:
  push:
    branches:
      - "main"
      - "[0-9].*"

name: Tests

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.operating-system }} with PHP ${{ matrix.php-version }}

    strategy:
      matrix:
        operating-system:
          - 'ubuntu-latest'
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: curl
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: composer install --no-interaction --no-progress --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit
